### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by ZucchiniZe** [ZucchiniZe/preworkhub#1]
## Todo list
- [ ] create previous and next methods on the video model that use the video num and class date to figure shit out
- [ ] after the video gets saved, find the duration of the video and save it as well
- [ ] add the markdownification of all of the `TextField`s.
- [ ] add handouts stuff to the prework app
- [ ] figure out how to handle days of performance tasks -- there are no prework videos for those days.
- [ ] deployment
  - [ ] figure out static files
  - [ ] setup environment variable config
  - [ ] figure out what it will cost
- [ ] frontend work
  - [ ] add a calendar view of all of the classes that is clickable
  - [ ] make it usable
  - [ ] make it pretty
